# Generated by Django 5.0.1 on 2024-02-02 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Receipient', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('NIGERIAN NAIRA', 'Nigerian Naira'), ('RUSSIAN ROUBLE', 'Russian Rouble')], max_length=225)),
                ('bank_name', models.CharField(max_length=225)),
                ('account_name', models.CharField(blank=True, max_length=225, null=True)),
                ('account_number', models.CharField(max_length=225)),
                ('phone_number', models.CharField(max_length=225)),
                ('card_number', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=225)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=225)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('content', models.TextField()),
                ('job', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=225, null=True)),
                ('site_title', models.CharField(blank=True, max_length=225, null=True)),
                ('nigerian_bank_name', models.CharField(blank=True, help_text='Name of Nigerian bank', max_length=225, null=True)),
                ('nigerian_bank_account_holder_name', models.CharField(blank=True, help_text='Name of nigerian bank account holder', max_length=225, null=True)),
                ('nigerian_bank_account_number', models.CharField(blank=True, help_text='Account number for the nigerian bank account', max_length=225, null=True)),
                ('russian_bank_name', models.CharField(blank=True, help_text='Name of bank', max_length=225, null=True)),
                ('russian_bank_account_holder_name', models.CharField(blank=True, help_text='Name of russian bank account holder', max_length=225, null=True)),
                ('russian_card_number', models.CharField(blank=True, help_text='Card number for the russian bank account', max_length=225, null=True)),
                ('russian_phone_number', models.CharField(blank=True, help_text='Phone number for the russian bank account', max_length=225, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('whatsapp_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=225, null=True)),
                ('footer_message', models.TextField(blank=True, null=True)),
                ('contact_page_message', models.TextField(blank=True, help_text='Can be ignored', null=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=225)),
                ('to_currency', models.CharField(max_length=225)),
                ('current_exchange_rate', models.FloatField(blank=True, max_length=225, null=True)),
                ('amount', models.FloatField()),
                ('transaction_id', models.CharField(max_length=225)),
                ('converted_amount', models.FloatField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('has_receipient', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Receipient.userrecipient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
