# Generated by Django 5.0.1 on 2024-01-17 23:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Globals', '0003_transaction_has_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('0333b910-46bd-4d20-a2e9-1f0ebd0c61c4'), max_length=225),
        ),
    ]
