# Generated by Django 5.0.1 on 2024-01-17 23:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Globals', '0004_transaction_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='comverted_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='converted_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('adf231cd-f4d6-469b-a447-ad30ad118152'), max_length=225),
        ),
    ]
