# Generated by Django 5.0.1 on 2024-01-18 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Globals', '0005_remove_transaction_comverted_amount_and_more'),
        ('Receipient', '0002_rename_uerrecipients_userrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Receipient.userrecipient'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('fdc6a77c-4307-4780-a3a3-d49a7e456a91'), max_length=225),
        ),
    ]
