# Generated by Django 5.0.1 on 2024-01-18 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Globals', '0008_transaction_current_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='current_exchange_rate',
            field=models.FloatField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('b61bb63b-62e5-4e92-a1ae-14396f9b618d'), max_length=225),
        ),
    ]
