# Generated by Django 5.0.1 on 2024-01-18 12:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Globals', '0009_alter_transaction_current_exchange_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('NIGERIAN NAIRA', 'Nigerian Naira'), ('RUSSIAN ROUBLE', 'Russian Rouble')], max_length=225)),
                ('bank_name', models.CharField(max_length=225)),
                ('account_name', models.CharField(blank=True, max_length=225, null=True)),
                ('account_number', models.CharField(max_length=225)),
                ('phone_number', models.CharField(max_length=225)),
                ('card_number', models.CharField(max_length=225)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('cd7d6b5f-87d7-4b43-bac4-737d39a334e3'), max_length=225),
        ),
    ]
