# Generated by Django 5.0.1 on 2024-01-18 14:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Globals', '0012_alter_transaction_transaction_id_siteinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('3cd05cd2-7cce-49c6-9b0a-39dd9606384e'), max_length=225),
        ),
    ]
