# Generated by Django 5.0.1 on 2024-01-18 14:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Globals', '0013_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('d8132993-816c-4158-a3f9-16bd05ad0d57'), max_length=225),
        ),
    ]
