# Generated by Django 5.0.1 on 2024-01-20 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Globals', '0014_siteinformation_whatsapp_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, help_text='Name of bank account holder', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Name of bank', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='nigerian_bank_account_number',
            field=models.CharField(blank=True, help_text='Account number for the nigerian bank account', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='russian_card_number',
            field=models.CharField(blank=True, help_text='Card number for the russian bank account', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='russian_phone_number',
            field=models.CharField(blank=True, help_text='Phone number for the russian bank account', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('3cb19423-0610-4476-8437-ae612224ba23'), max_length=225),
        ),
    ]
