# Generated by Django 5.0.1 on 2024-01-20 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Globals', '0015_siteinformation_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinformation',
            old_name='bank_name',
            new_name='russian_bank_name',
        ),
        migrations.RemoveField(
            model_name='siteinformation',
            name='bank_account_holder_name',
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='nigerian_bank_account_holder_name',
            field=models.CharField(blank=True, help_text='Name of nigerian bank account holder', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='nigerian_bank_name',
            field=models.CharField(blank=True, help_text='Name of Nigerian bank', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='russian_bank_account_holder_name',
            field=models.CharField(blank=True, help_text='Name of russian bank account holder', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('255090d2-b03e-426a-bf51-6a9cac299f4c'), max_length=225),
        ),
    ]
