# Generated by Django 5.0.1 on 2024-01-20 10:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Globals', '0016_rename_bank_name_siteinformation_russian_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('8de02737-6c61-4662-a033-a192ed2536a3'), max_length=225),
        ),
    ]
