# Generated by Django 5.0.1 on 2024-01-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Globals', '0018_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('content', models.TextField()),
                ('job', models.CharField(max_length=225)),
            ],
        ),
    ]
