# Generated by Django 5.0.1 on 2024-01-17 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UerRecipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=225)),
                ('account_name', models.CharField(blank=True, max_length=225, null=True)),
                ('account_number', models.CharField(max_length=225)),
                ('phone_number', models.CharField(max_length=225)),
                ('card_number', models.CharField(max_length=225)),
                ('transfer_type', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
