# Generated by Django 5.0.1 on 2024-01-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipient', '0002_rename_uerrecipients_userrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecipient',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
